Part 4: Add Codesandbox examples for DX Integration tests and Examples
americanexpress/fetchye pull request #11
Opened 2020-09-07 22:57 UTC by mtomcal

* Added Codesandboxes for the various install configurations and Next.JS SSR

2020-09-08 03:39 UTC, 10xLaCroixDrinker reviewed
This latest commit LGTM, just pending the preceding PRs

2020-09-08 20:29 UTC, JamesSingleton approved these changes

2020-09-15 22:57 UTC, JamesSingleton submitted a review, later dismissed

2020-09-15 22:58 UTC, Francois-Esquire approved these changes

2020-09-15 23:08 UTC, JAdshead requested changes

2020-09-15 23:08 UTC, JAdshead commented on examples/next-js/fetchye-ssr/README.md
> +# Hello World example
Don't think this README should be here

2020-09-15 23:19 UTC, JAdshead approved these changes

2020-09-15 23:37 UTC, JamesSingleton approved these changes

2020-09-15 23:39 UTC, merged

2020-09-17 23:35 UTC, mtomcal commented
:tada: This PR is included in version 1.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/fetchye/v/1.0.0-beta.1)
- [GitHub release](https://github.com/americanexpress/fetchye/releases/tag/v1.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: