fix(makeServerFetchye): mask errors from server side fetching
americanexpress/fetchye pull request #49
Opened 2021-07-20 13:01 UTC by code-forger

When a fetch fails in SSR, we now drop the error entirely. This prevents unserializable Errors ending up in the redux store. 

This also provides a better behaviour for SSR where failed fetches still render a loading state, allowing the browser to 'try again' fetching the data

## Motivation and Context
This removes a 'cannot serialize' error from being emitted on the server when a fetch fails.

## How Has This Been Tested?
Using a local instance of one app and some test modules I have proved that SSR now renders a 'loading' state of the application, without logging 'cannot serialize' errors, when a fetch fails in the server.
I have Unit test coverage for all new code.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] My changes are in sync with the code style of this project.
- [x] There aren't any other open Pull Requests for the same issue/update.
- [ ] These changes should be applied to a maintenance branch.
- [x] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using Fetchye?
None

2021-07-20 22:28 UTC, JAdshead approved these changes
I am happy to always have another attempt in the client if it errors on the server.

2021-07-21 19:02 UTC, 10xLaCroixDrinker requested changes

2021-07-23 11:46 UTC, code-forger commented on packages/fetchye-core/__tests__/ssrFetcher.spec.js
> + * Copyright 2020 American Express Travel Related Services Company, Inc.
address in 2e59af6

2021-07-23 11:46 UTC, code-forger commented on packages/fetchye-core/src/ssrFetcher.js
> + * Copyright 2020 American Express Travel Related Services Company, Inc.
address in 2e59af6

2021-07-23 11:46 UTC, code-forger commented on packages/fetchye-core/__tests__/ssrFetcher.spec.js
> +    expect(defaultFetcher).toMatchSnapshot();
It was validating that the parameters passed to ssrFetcher were forwarded to defaultFetcher.
address in 2e59af6

2021-07-23 16:00 UTC, JAdshead approved these changes

2021-07-23 16:48 UTC, 10xLaCroixDrinker approved these changes

2021-07-23 17:29 UTC, merged