fix(reduxProvider): dependency array had bad entry
americanexpress/fetchye pull request #73
Opened 2023-04-04 22:08 UTC by Matthew-Mallimo

## Description

The dependency array for the useEffect in `makeUseFetchyeSelector` included a functional reference that was only updated when the `key` changes. In certain circumstances where data fetching is started by another process (not useFetchye), this useEffect would fail to run once the data was returned.

Implementing this actually reduced the number of renders. 

## Motivation and Context

This change correctly reruns the useEffect when data has changed.

## How Has This Been Tested?

Unit tests, and manual testing.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] My changes are in sync with the code style of this project.
- [ ] There aren't any other open Pull Requests for the same issue/update.
- [ ] These changes should be applied to a maintenance branch.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using Fetchye?

2023-04-04 22:58 UTC, 10xLaCroixDrinker commented
Can you include a unit test that would fail without this fix?

2023-04-05 11:26 UTC, code-forger approved these changes

2023-04-05 16:58 UTC, JAdshead approved these changes

2023-04-05 17:03 UTC, 10xLaCroixDrinker requested changes
Please add a unit test that fails without this fix

2023-04-05 20:51 UTC, JAdshead approved these changes

2023-04-05 21:53 UTC, merged