feat(signal): remove passed signal from defautlMapOptionsToKey
americanexpress/fetchye pull request #83
Opened 2023-08-03 18:51 UTC by dogpatch626

## Description

add support for abortController by allowing a signal to be passed as an option 
## Motivation and Context

## How Has This Been Tested?

tested locally passing signal as options 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)
- [ ] Dependency update

## Checklist:

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] My changes are in sync with the code style of this project.
- [ ] There aren't any other open Pull Requests for the same issue/update.
- [ ] These changes should be applied to a maintenance branch.
- [ ] I have added the Apache 2.0 license header to any new files created.

## What is the Impact to Developers Using Fetchye?

2023-08-07 11:44 UTC, code-forger commented on packages/fetchye/src/defaultMapOptionsToKey.js
> +    signal,
Can you make a unit tests that calls this function with this name and shows that it is removed.

One that would fail if this change was reverted

2023-08-08 19:46 UTC, 10xLaCroixDrinker requested changes
Add unit test

2023-08-21 19:00 UTC, JAdshead commented on README.md
> +const { isLoading, data, error, run } = useFetchye(key, { signal: {}, defer: Boolean, mapOptionsToKey: options => options, ...fetchOptions }, fetcher);
signal is a fetch api not fetchye so should be removed from here.

```suggestion
const { isLoading, data, error, run } = useFetchye(key, { defer: Boolean, mapOptionsToKey: options => options, ...fetchOptions }, fetcher);
```

2023-08-21 19:02 UTC, JAdshead commented on README.md
> +| `signal`           | `Object`                                              | `false`  | Prevents execution of `useFetchye` when desired cancelling DOM request (See [Abort Controller](https://develo
```suggestion
```

2023-08-21 19:05 UTC, JAdshead commented on README.md
> +### Abort Signal
Im not sure that this should be documented in this mannor, else the readme should document all of the fetch apis. 
Maybe this should be framed as an example of aborting an inflight request on unmount.

2023-08-21 19:06 UTC, JAdshead requested changes
Update documentation based on comments.

2023-08-21 20:43 UTC, Matthew-Mallimo commented on README.md
> +pass a signal as an option in such way.
```suggestion
pass a signal as an option, as demonstrated below.
```

2023-08-24 21:23 UTC, 10xLaCroixDrinker approved these changes

2023-08-24 22:46 UTC, JAdshead approved these changes

2023-08-24 22:46 UTC, merged